services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: homestore-sqlserver
    hostname: homestore-sqlserver
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
    volumes:
      - homestore_sqlserver_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  homestore_sqlserver_data:
